blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
    path('', views.blog_view, name="blog_view"),
    path('buat', views.buat_blog, name="form_blog"),
    path('delete/<id>', views.blog_delete, name="hapus"),
]

eclair_project/urls.py
from django.contrib import admin
from django.urls import path, include
from home_app.views import *
from beli_ikan.views import *
from django.conf import settings
from django.conf.urls.static import static 
from toko.views import *
from faq.views import *
from blog.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home_app.urls')),
    path('toko/', include('toko.urls')),
    path('beli/', include('beli_ikan.urls')),
    path('faq/', include('faq.urls')),
    path('blog/', include('blog.urls') )

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

faq/urls.py
from django.urls import path
from . import views

app_name = "faq"
urlpatterns = [
    path('', views.pertanyaan, name="faq"),
    #path('faq/', views.pertanyaan , name="faq")
]

blog/models.py
from django.db import models

class BlogModels(models.Model):

    judul = models.CharField(max_length=120)
    deskripsi = models.CharField(max_length=500)
    foto = models.ImageField(upload_to='foto_blog/')

    def __str__(self):
        return self.judul

# Create your models here.

blog/forms.py
from django.forms import ModelForm
from .models import BlogModels

class BlogModelsForms(ModelForm):
    class Meta:
        model = BlogModels
        fields = [
            'judul',
            'deskripsi',
            'foto',
        ]

blog/views.py
from django.shortcuts import render
from .forms import BlogModelsForms
from .models import BlogModels
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
def buat_blog(request):
    
    if(request.method == 'POST'):
        form = BlogModelsForms(request.POST, request.FILES)
        if(form.is_valid()):
            form.save()
            return redirect ('blog:form_blog')
    else:
        form = BlogModelsForms()
        context = {
            'form':form,
            'all_response':BlogModels.objects.all(),
        }
        return render(request,"buat_blog.html",context)   

def blog_view(request):
    data = BlogModels.objects.all()
    return render(request, 'view_blog.html', {'data': data})

def blog_delete(request, id):
    blog_hapus = BlogModels.objects.get(id=id)
    blog_hapus.delete()
    return redirect('blog:blog_view')

blog/templates/buat_blog.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} Blog {% endblock %}
{% block isi %}

<div class="container">
    <div class="d-flex justify-content-center h-100">
        <div class="card form-buatIkan">
            <h5 class="card-header header-form">Tambah Post</h5>
            <div class="card-body">
                <form action="/blog/buat" enctype="multipart/form-data" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form.judul|as_crispy_field }}
                    </div>
                    <div class="form-group">
                        {{ form.foto|as_crispy_field }}            
                    </div>
                    <div class="form-group">
                        {{ form.deskripsi|as_crispy_field }}             
                    </div>
                        <button type="submit" class="btn btn-light" id="btn-tambahBlog">Tambah Post</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock isi %}

blog/templates/view_blog.html
{% extends "base.html" %}
{% load static %}
{% block title %} Post {% endblock %}
{% block isi %}
<head>
    <link rel = "stylesheet" type = "text/css"  href = "{% static 'blog.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Poppins&display=swap" rel="stylesheet">
</head>
<body>
    <div class="hal_blog">
    {% if data %}
        {% for object_isian in data %}
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row no-gutters">
                    <div class="col-md-4">
                        <img src="{{ object_isian.foto.url }}" class="card-img foto-blog" alt="image">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body persegmen">
                            <h5 class="card-title judul">{{ object_isian.judul }}</h5>
                            <p class="card-text deskripsi">{{ object_isian.deskripsi }}</p>
                            <p><a href= "{% url 'blog:hapus' id=object_isian.id %} "> <button type="submit">Hapus</button> </a></p>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <h1>Belum ada Post</h1>
    {% endif %}
        <a href="{% url 'blog:form_blog' %}"><button type="button" class="btn btn-light" id="btn-buat_post">Tulis Post Baru</button></a>
    

    </div>
    
    {% endblock isi %}

</body>
    