beli_ikan/urls.py
from django.urls import path
from . import views

app_name = "beli_ikan"
urlpatterns = [
    path('', views.daftar_Ikan, name="form_ikan"),
    path('terima', views.buat_Ikan, name="terima"),
    path('delete/<id>', views.hapus_Ikan, name="hapus"),
]

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
    path('', views.blog_view, name="blog_view"),
    path('buat', views.buat_blog, name="form_blog"),
    path('delete/<id>', views.blog_delete, name="hapus"),
]

eclair_project/urls.py
from django.contrib import admin
from django.urls import path, include
from home_app.views import *
from beli_ikan.views import *
from django.conf import settings
from django.conf.urls.static import static 
from toko.views import *
from faq.views import *
from blog.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home_app.urls')),
    path('toko/', include('toko.urls')),
    path('beli/', include('beli_ikan.urls')),
    path('faq/', include('faq.urls')),
    path('blog/', include('blog.urls') )

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

faq/urls.py
from django.urls import path
from . import views

app_name = "faq"
urlpatterns = [
    path('', views.pertanyaan, name="faq"),
    #path('faq/', views.pertanyaan , name="faq")
]

home_app/urls.py
from django.urls import path
from . import views

app_name = "home_app"
urlpatterns = [
    path('', views.home, name="beranda"),
]

blog/models.py
from django.db import models

class BlogModels(models.Model):

    judul = models.CharField(max_length=120)
    deskripsi = models.CharField(max_length=500)
    foto = models.ImageField(upload_to='foto_blog/')

    def __str__(self):
        return self.judul

# Create your models here.

home_app/models.py
from django.db import models

# Create your models here.

blog/forms.py
from django.forms import ModelForm
from .models import BlogModels

class BlogModelsForms(ModelForm):
    class Meta:
        model = BlogModels
        fields = [
            'judul',
            'deskripsi',
            'foto',
        ]

blog/views.py
from django.shortcuts import render
from .forms import BlogModelsForms
from .models import BlogModels
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
def buat_blog(request):
    
    if(request.method == 'POST'):
        form = BlogModelsForms(request.POST, request.FILES)
        if(form.is_valid()):
            form.save()
            return redirect ('blog:form_blog')
    else:
        form = BlogModelsForms()
        context = {
            'form':form,
            'all_response':BlogModels.objects.all(),
        }
        return render(request,"buat_blog.html",context)   

def blog_view(request):
    data = BlogModels.objects.all()
    return render(request, 'view_blog.html', {'data': data})

def blog_delete(request, id):
    blog_hapus = BlogModels.objects.get(id=id)
    blog_hapus.delete()
    return redirect('blog:blog_view')

home_app/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, "beranda.html")

home_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>{% block title %}{% endblock %} - Eclair Lake</title>
    {% block head %}{% endblock%}
</head>
<body>
    <nav class="navbar navbar-light navbar-expand-md bg-light justify-content-center">
        <button class="navbar-toggler ml-1" type="button" data-toggle="collapse" data-target="#collapsingNavbar2">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse justify-content-between align-items-center w-100" id="collapsingNavbar2">
            <ul class="navbar-nav mx-auto text-center">
                {% with url_name=request.resolver_match.url_name %}
                <li class="nav-item {% if url_name == 'form_ikan' %} active {% endif %}">
                    <a class="nav-link" href="{% url 'beli_ikan:form_ikan' %}">Beli</a>
                </li>
                <li class="nav-item {% if url_name == 'toko' %} active {% endif %}">
                    <a class="nav-link" href="/toko/">Toko</a>
                </li>
                <a href="{% url 'home_app:beranda' %}" class="{% if url_name == 'beranda' %} active {% endif %}"><img class="logo-navbar" src="{% static 'images/logo-eclair.png' %}"></a>
                <li class="nav-item">
                    <a class="nav-link" href="/blog/">Blog</a> 
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'faq:faq' %}">FAQ</a> 
                </li>
                {% endwith %}
            </ul>
        </div>
    </nav>
            
    {% block isi %}{% endblock %}

    <div class="footer">
        <p id="copri">©Eclair-lake</p>
        <div class="logo">
            <a href="https://id-id.facebook.com/"><img class="logo-item" src="{% static 'images/FB.png' %}"></a>
            <a href="https://www.instagram.com/"><img class="logo-item" src="{% static 'images/IG.png' %}"></a>
            <a href="https://id.linkedin.com/"><img class="logo-item" src="{% static 'images/LinkedIN.png' %}"></a>
            <a href="https://wa.me/"><img class="logo-item" src="{% static 'images/WA.png' %}"></a>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

home_app/templates/beranda.html
{% extends "base.html" %}
{% load static %}

{% block title %} Beranda {% endblock %}

{% block head %}
<link href="https://fonts.googleapis.com/css?family=Poppins:400,400i&display=swap" rel="stylesheet"> 
{% endblock %}

{% block isi %}
<div class=".container nelayan">
    <div class="text text-center">
        <h1>Ikan<br>Segar?</h1>
    </div>    
</div>

<div class="container-fluid bg-biru">
    <div class="ikan-float">
        <img src="{% static 'images/ikan_desc_eclair.png' %}">
    </div>
    <div class="row">
        <div class="col text-ikan ukur">
            <h1>Apa itu Eclair?</h1>
            <p>Eclair adalah sebuah website yang memfasilitasi transaksi 
                antara nelayan dengan pembeli ikan.</p>
        </div>
    </div>
    
</div>

<div class="container-fluid full-layar">
    <div class="row">
        <div class="col-6 text-kenapa ukur">
            <h1>Mengapa Eclair?</h1>
            <p>Karena dengan Eclair, anda akan mendapatkan ikan segar langsung dari nelayan.   Eclair juga menyediakan informasi atau fakta mengenai ikan bagi anda yang masih bingung ingin membeli ikan apa.</p>
        </div>
        <div class="col-6 penuhin">
        </div>
    </div>
</div>

<div class="container-fluid bg-biru display-centered ujung-bawah">
    <h1 class="tengah-tengah">Testimoni pengguna Eclair</h1>
    <div class="row">
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <p class="card-text">Ikan yang disediakan Eclair sangat segar dan pengantarannya pun tepat waktu. </p>
                <p class="card-text"></p>
                <p class="card-text">Terima kasih Eclaire!</p>
                <p class="card-text">Pengguna1</p>
            </div>
        </div>
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <p class="card-text">Ikan yang disediakan Eclair sangat segar dan pengantarannya pun tepat waktu. </p>
                <p class="card-text"></p>
                <p class="card-text">Terima kasih Eclaire!</p>
                <p class="card-text">Pengguna1</p>
            </div>
        </div>
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <p class="card-text">Ikan yang disediakan Eclair sangat segar dan pengantarannya pun tepat waktu. </p>
                <p class="card-text"></p>
                <p class="card-text">Terima kasih Eclaire!</p>
                <p class="card-text">Pengguna1</p>
            </div>
        </div>
    </div>
</div>
{% endblock isi %}

home_app/templates/blog.html
{% extends "base.html" %}
{% load static %}

{% block title %} Beranda {% endblock %}