beli_ikan/urls.py
from django.urls import path
from . import views

app_name = "beli_ikan"
urlpatterns = [
    path('', views.daftar_Ikan, name="form_ikan"),
    path('terima', views.buat_Ikan, name="terima"),
    path('delete/<id>', views.hapus_Ikan, name="hapus"),
]

eclair_project/urls.py
from django.contrib import admin
from django.urls import path, include
from home_app.views import *
from beli_ikan.views import *
from django.conf import settings
from django.conf.urls.static import static 
from toko.views import *
from faq.views import *
from blog.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home_app.urls')),
    path('toko/', include('toko.urls')),
    path('beli/', include('beli_ikan.urls')),
    path('faq/', include('faq.urls')),
    path('blog/', include('blog.urls') )

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

faq/urls.py
from django.urls import path
from . import views

app_name = "faq"
urlpatterns = [
    path('', views.pertanyaan, name="faq"),
    #path('faq/', views.pertanyaan , name="faq")
]

beli_ikan/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from toko.models import Toko

class Ikan(models.Model):
    jenis = models.CharField(max_length = 100)
    foto = models.ImageField(upload_to='images/')
    harga = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(9223372036854775807)])
    deskripsi = models.TextField(max_length = 100)
    namaToko = models.ManyToManyField(Toko)

    def __str__(self):
        return self.jenis

beli_ikan/forms.py
from django import forms
from . import models

class BuatIkan(forms.ModelForm):
    class Meta:
        model = models.Ikan
        fields = ['jenis', 'foto', 'harga', 'deskripsi', 'namaToko']

beli_ikan/views.py
from django.shortcuts import render, redirect
from . import forms
from .models import Ikan

def buat_Ikan(request):
    if request.method == 'POST':
        form = forms.BuatIkan(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect ('beli_ikan:form_ikan')
    else:
        form = forms.BuatIkan()
        return render(request, 'buat_ikan.html', {'form_ikan':form})

def daftar_Ikan(request):
    if request.method=='POST':
        form = forms.BuatIkan(request.POST)
        if form.is_valid():
            form.save()
        
    semua_ikan = Ikan.objects.all().order_by('jenis','harga')
    return render(request, "daftar_ikan.html", {'semua_ikan':semua_ikan})

def hapus_Ikan(request, id):
    ikan_hapus = Ikan.objects.get(id=id)
    ikan_hapus.delete()
    return redirect('beli_ikan:form_ikan')

beli_ikan/templates/buat_ikan.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} Daftar Ikan {% endblock %}
{% block isi %}

<div class="container">
    <div class="d-flex justify-content-center h-100">
        <div class="card form-buatIkan">
            <h5 class="card-header header-form">Tambah Ikan</h5>
            <div class="card-body">
                <form action="/beli/terima" enctype="multipart/form-data" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form_ikan.jenis|as_crispy_field }}
                    </div>
                    <div class="form-group">
                        {{ form_ikan.foto|as_crispy_field }}            
                    </div>
                    <div class="form-group">
                        {{ form_ikan.harga|as_crispy_field }}             
                    </div>
                    <div class="form-group">
                        {{ form_ikan.deskripsi|as_crispy_field }}          
                    </div>
                    <div class="form-group">
                        {{ form_ikan.namaToko|as_crispy_field }}
                    </div>
                    <button type="submit" class="btn btn-light" id="btn-tambahIkan">Tambah Ikan</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock isi %}

beli_ikan/templates/daftar_ikan.html
{% extends "base.html" %}
{% load static %}
{% block title %} Daftar Ikan {% endblock %}
{% block isi %}

    {% if semua_ikan %}
    <div class="row">
        {% for object_isian in semua_ikan %}
        <div class="card" style="width: 18rem;">
            <img src="{{ object_isian.foto.url }}" class="card-img-top" alt="image">
            <div class="card-body">
                <p class="card-text">{{ object_isian.jenis }}</p>
                <p class="card-text">{{ object_isian.harga }}</p>
                <p class="card-text">{{ object_isian.deskripsi }}</p>
                <p class="card-text">{% for nama in object_isian.namaToko.all %} {{ nama }} {% endfor %}</p>
                <p><a href= "{% url 'beli_ikan:hapus' id=object_isian.id %} "> <button type="submit">Hapus</button> </a></p>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
        <h1>Belum ada Ikan</h1>
    {% endif %}
    <a href="{% url 'beli_ikan:terima' %}"><button type="button" class="btn btn-light" id="btn-buat_ikan">Daftar Ikan Baru</button></a>

{% endblock isi %}